"""alert and alert_delivery

Revision ID: 19a51d67356f
Revises: 617e4bc1dab1
Create Date: 2026-04-25 22:11:19.318902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a51d67356f'
down_revision: Union[str, Sequence[str], None] = '617e4bc1dab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('alert_id', sa.String(length=26), nullable=False),
    sa.Column('ngo_id', sa.String(length=26), nullable=False),
    sa.Column('person_name', sa.String(length=200), nullable=False),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('last_seen_geohash', sa.String(length=12), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region_geohash_prefix', sa.String(length=12), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('urgency_tier', sa.String(length=16), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.ngo_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('alert_delivery',
    sa.Column('delivery_id', sa.String(length=26), nullable=False),
    sa.Column('ngo_id', sa.String(length=26), nullable=False),
    sa.Column('alert_id', sa.String(length=26), nullable=False),
    sa.Column('recipient_phone', sa.String(length=32), nullable=False),
    sa.Column('out_id', sa.String(length=26), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert_id'], ),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.ngo_id'], ),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_delivery')
    op.drop_table('alert')
    # ### end Alembic commands ###
