"""outbound_message sighting

Revision ID: 3b9aea834a80
Revises: 970f8654f471
Create Date: 2026-04-25 22:22:53.711795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '3b9aea834a80'
down_revision: Union[str, Sequence[str], None] = '970f8654f471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sighting',
    sa.Column('sighting_id', sa.String(length=26), nullable=False),
    sa.Column('ngo_id', sa.String(length=26), nullable=False),
    sa.Column('alert_id', sa.String(length=26), nullable=False),
    sa.Column('observer_phone', sa.String(length=32), nullable=False),
    sa.Column('geohash', sa.String(length=12), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('photo_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert_id'], ),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.ngo_id'], ),
    sa.PrimaryKeyConstraint('sighting_id')
    )
    op.create_table('outbound_message',
    sa.Column('out_id', sa.String(length=26), nullable=False),
    sa.Column('ngo_id', sa.String(length=26), nullable=False),
    sa.Column('tool_call_id', sa.String(length=26), nullable=True),
    sa.Column('recipient_phone', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_msg_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('previous_out_id', sa.String(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.ngo_id'], ),
    sa.ForeignKeyConstraint(['previous_out_id'], ['outbound_message.out_id'], ),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_call.call_id'], ),
    sa.PrimaryKeyConstraint('out_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbound_message')
    op.drop_table('sighting')
    # ### end Alembic commands ###
