"""identity tables

Revision ID: 617e4bc1dab1
Revises: ea838bdca944
Create Date: 2026-04-25 22:05:51.555145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617e4bc1dab1'
down_revision: Union[str, Sequence[str], None] = 'ea838bdca944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngo',
    sa.Column('ngo_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region_geohash_prefix', sa.String(length=12), nullable=True),
    sa.Column('standing_orders', sa.Text(), nullable=True),
    sa.Column('operator_pubkey', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ngo_id')
    )
    op.create_table('account',
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('ngo_id', sa.String(length=26), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('home_geohash', sa.String(length=12), nullable=True),
    sa.Column('last_known_geohash', sa.String(length=12), nullable=True),
    sa.Column('push_token', sa.String(length=512), nullable=True),
    sa.Column('app_last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('channel_pref', sa.String(length=16), nullable=False),
    sa.Column('sms_fallback_after_seconds', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.ngo_id'], ),
    sa.PrimaryKeyConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.drop_table('ngo')
    # ### end Alembic commands ###
