"""agent_decision tool_call

Revision ID: 970f8654f471
Revises: d0628efac96e
Create Date: 2026-04-25 22:19:03.014345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '970f8654f471'
down_revision: Union[str, Sequence[str], None] = 'd0628efac96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_decision',
    sa.Column('decision_id', sa.String(length=26), nullable=False),
    sa.Column('ngo_id', sa.String(length=26), nullable=False),
    sa.Column('bucket_key', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('turns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bucket_key'], ['bucket.bucket_key'], ),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.ngo_id'], ),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('bucket_key', name='uq_agent_decision_bucket_key')
    )
    op.create_table('tool_call',
    sa.Column('call_id', sa.String(length=26), nullable=False),
    sa.Column('ngo_id', sa.String(length=26), nullable=False),
    sa.Column('decision_id', sa.String(length=26), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('approval_status', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revised_from_call_id', sa.String(length=26), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.String(length=64), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['agent_decision.decision_id'], ),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.ngo_id'], ),
    sa.ForeignKeyConstraint(['revised_from_call_id'], ['tool_call.call_id'], ),
    sa.PrimaryKeyConstraint('call_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_tool_call_idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_call')
    op.drop_table('agent_decision')
    # ### end Alembic commands ###
