"""inbound_message triaged_message bucket

Revision ID: d0628efac96e
Revises: 19a51d67356f
Create Date: 2026-04-25 22:15:03.521766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'd0628efac96e'
down_revision: Union[str, Sequence[str], None] = '19a51d67356f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucket',
    sa.Column('bucket_key', sa.String(length=128), nullable=False),
    sa.Column('ngo_id', sa.String(length=26), nullable=False),
    sa.Column('alert_id', sa.String(length=26), nullable=False),
    sa.Column('geohash_prefix_4', sa.String(length=4), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_length_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('claimed_by', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert_id'], ),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.ngo_id'], ),
    sa.PrimaryKeyConstraint('bucket_key')
    )
    op.create_table('inbound_message',
    sa.Column('msg_id', sa.String(length=26), nullable=False),
    sa.Column('ngo_id', sa.String(length=26), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('sender_phone', sa.String(length=32), nullable=False),
    sa.Column('in_reply_to_alert_id', sa.String(length=26), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['in_reply_to_alert_id'], ['alert.alert_id'], ),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.ngo_id'], ),
    sa.ForeignKeyConstraint(['sender_phone'], ['account.phone'], ),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('triaged_message',
    sa.Column('msg_id', sa.String(length=26), nullable=False),
    sa.Column('ngo_id', sa.String(length=26), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('geohash6', sa.String(length=12), nullable=True),
    sa.Column('geohash_source', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('duplicate_of', sa.String(length=26), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('bucket_key', sa.String(length=128), nullable=False),
    sa.Column('body_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['msg_id'], ['inbound_message.msg_id'], ),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.ngo_id'], ),
    sa.PrimaryKeyConstraint('msg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triaged_message')
    op.drop_table('inbound_message')
    op.drop_table('bucket')
    # ### end Alembic commands ###
