"""bad_actor

Revision ID: e3fbe7836f3b
Revises: 56b172f18299
Create Date: 2026-04-25 22:30:53.240083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3fbe7836f3b'
down_revision: Union[str, Sequence[str], None] = '56b172f18299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bad_actor',
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('ngo_id', sa.String(length=26), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('marked_by', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.ngo_id'], ),
    sa.PrimaryKeyConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bad_actor')
    # ### end Alembic commands ###
